### ISSUE TITLE
Not able to generate project using Tuist

### ISSUE THREAD

**Issue by blueberry404** [GetStream/twitter-clone#57]
I am new to Tuist and while following your [tutorial](https://getstream.io/resources/projects/twitter-clone/building-the-timeline/), I am not able to generate Tuist project using `tuist generate` command. I am getting error as:

> 
> Resolved cache profile 'Development' from Tuist's defaults
> No files found at: .../ios/twitter-clone/TwitterClone/Targets/Auth/Resources/**
> No files found at: .../ios/twitter-clone/TwitterClone/Targets/Keychain/Resources/**
> `StreamChatSwiftUI` is not a valid configured external dependency for platform ios

Is there any pre-configuration required in order to generate the project? I doubt that manifest file might need a fix. Thanks

**Comment by jeroenleenarts** [comment]
Hi... Most likely you forgot to run `tuist fetch` could you try that before running `tuist generate`?

**Comment by blueberry404** [comment]
Thanks, it's working now!
